---
title: "Multi Method Comparison"
author: "Javier Rey"
date: '`r Sys.Date()`'
output: pdf_document
---

```{r dataframe, comment = '', echo=FALSE, warning = FALSE, message = FALSE}
library(mcr)

data_loaded = data()
        
methods = c("LinReg", "WLinReg", "Deming", "WDeming", "PaBa")

slopes = c()
models = c()
intercepts = c()
for (method in methods) {
    x = data_loaded$reference
    y = data_loaded %>% dplyr::select(!!input$method_list) %>% pull()
    model = mcr::mcreg(x, y, method.reg=method, mref.name="Reference",
                       mtest.name="Test", na.rm=TRUE)
    slopes = c(slopes, mcr::getCoefficients(model)[2])
    intercepts = c(intercepts, mcr::getCoefficients(model)[1])
    models = c(models, method)
}
df_for_models = data.frame(slope = slopes,
                           intercept = intercepts,
                           model = models)

p = ggplot(data = data_loaded, aes(x = reference, y = y)) + 
    geom_point() +
    geom_abline(data=df_for_models, mapping=aes(slope=slope, intercept=intercept, color=model)) +
    # Identity line
    geom_abline(slope=1, intercept=0, color="red") +
    labs(y=input$method_list) +
    theme_bw(base_size = 12)
p
```

#### Data is processed using R language^1^, shiny web application framework^2^ and mcr package^3^. Shinydashboard^4^and pander^5^ are used for website construction. Rmarkdown^6^ is used for converting results into PDF and HTML files.

##### References and packages:

1. R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. Version: `r getRversion()` URL: https://www.R-project.org
2. shiny: Web Application Framework for R. Version `r packageDescription("shiny")$Version` URL: http://CRAN.R-project.org/package=shiny
3. mcr: Method Comparison Regression. Version: `r packageDescription("mcr")$Version` URL: http://CRAN.R-project.org/package=mcr
4. shinydashboard: Create Dashboards with 'Shiny'. Version: `r packageDescription("shinydashboard")$Version` URL: http://rstudio.github.io/shinydashboard
5. pander: An R Pandoc Writer. Version: `r packageDescription("pander")$Version` URL: http://rapporter.github.io/pander
6. rmarkdown: Dynamic Documents for R. Version: `r packageDescription("rmarkdown")$Version` URL: http://rmarkdown.rstudio.com


$Y=\beta _{0}+\beta _{1}X_{1}+\cdots +\beta _{m}X_{m}+\varepsilon }$

